#name: Build RUM Project
#on: [push]

#jobs:
#  build:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2

#    - name: Install dependencies
#      run: npm ci

#    - name: Build project
#      run: npm run build

name: Build and Test

on:
  push:
    branches:
      - main  # Replace with the branch name you want to trigger the workflow on

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Choose the appropriate runner for your needs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # NODE JS version

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build RUM project
      working-directory: ./integration-tests/test-latest
      run: npm i && npm run build && npx serve dist &   #build me aplikace a zapnuti serveru

    - name: start playwright test
      working-directory: ./integration-tests/test-latest/playwright-tests
      run: npx playwright test               #run playwright tests



    # - name: Copy latest.js file
    #   #run: cp path/to/latest.js . #zde bude cesta od cdn/latest do /test-latest

    # - name: Start Vite + Preact project
    #   #neccesery path     ./integration-tests/test-latest
    #   working-directory: ./integration-tests/test-latest
    #   run: npm ci         #It is neccessery to install packages for vite
    #   run: npm run dev              # vite project start

    # - name: Run Playwright tests
    #   #neccesery path     ./integration-tests/test-latest/playwright-tests
    #   working-directory: ./integration-tests/test-latest/playwright-tests
    #   run: npm ci          #It is neccessery to install packages for playwright
    #   run: npx playwright test      # start playwright tests



