name: Copy Move latest.js
on: [push]

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy latest.js
      run: cp ../../cdn/latest.js ./integrat-tests/test-latest
